### ISSUE TITLE
code is not good enough for testing

### ISSUE THREAD

**Issue by sidharthsinghcfins** [aws-samples/aws-iam-access-key-auto-rotation#7]
Issue 1: This function seems to update secrets manager only in plaintext format not in key pair format.
Issue 2: if there is already an entry for user in key value pair in secrets manager , (let say when user is created via CF and updated to SM). those keys are not updated at all.

in both scenarios keys gets rotated and i get notification., but there is not key update on secrets manager.
i can confirm there is gap in the code and is partially running to even test for test scenarios. gap in this solution is implementation and how console or aws handles secrets in json format.

**Comment by aws-laura** [comment]
Issues 1 & 2 have been resolved with the new version 2 release.
